### ISSUE TITLE
Installing with Docker fails building cryptography

### ISSUE THREAD

**Issue by thiccpad** [searx/searx#2646]
**Version of Searx, commit number if you are using on master branch and stipulate if you forked Searx**
v0.18.0
**How did you install Searx?**
with the dockerfile from this github repository
**What happened?**
When trying to build from the dockerfile, it fails because the cryptography project now has a Rust dependency, since they are switching from C to Rust. 

**How To Reproduce**
Try building searx with Docker

**Expected behavior**
Building succeeds

**Screenshots & Logs**
```
 =============================DEBUG ASSISTANCE=============================
If you are seeing a compilation error please try the following steps to
successfully install cryptography:
1) Upgrade to the latest pip and try again. This will fix errors for most
users. See: https://pip.pypa.io/en/stable/installing/#upgrading-pip
2) Read https://cryptography.io/en/latest/installation.html for specific
instructions for your platform.
3) Check our frequently asked questions for more information:
https://cryptography.io/en/latest/faq.html
4) Ensure you have a recent Rust toolchain installed:
https://cryptography.io/en/latest/installation.html#rust
5) If you are experiencing issues with Rust for *this release only* you may
set the environment variable `CRYPTOGRAPHY_DONT_BUILD_RUST=1`.
=============================DEBUG ASSISTANCE=============================

error: Can not find Rust compiler
—————————————-
ERROR: Failed building wheel for cryptography
```

**Additional context**
From what I could gather, the issue arises, because you're still using Alpine Linux 3.12 in your dockerfile and Alpine 3.13 should have the appropriate version of Rust. The dockerfile should be updated. For further reading here: https://github.com/pyca/cryptography/issues/5771

**Comment by unixfox** [comment]
Could you create a pull request for fixing the dockerfile?

**Comment by dalf** [comment]
I can't reproduce this issue: `make docker`  works with Alpine 3.13.

---

`requests[security]` depends on `cryptography` but not `requests`.

See:
* https://docs.python-requests.org/en/latest/community/updates/#id2
* https://github.com/psf/requests/blob/2c2138e811487b13020eb331482fb991fd399d4e/setup.py#L102-L105
* https://github.com/searx/searx/blob/547478089f1a48bb22a7651435db6cf941afc2f5/requirements.txt#L11

With
```
$ pip install -r requirements.txt
....
Installing collected packages: certifi, pytz, babel, MarkupSafe, jinja2, itsdangerous, Werkzeug, click, flask, flask-babel, idna, lxml, pygments, six, python-dateutil, pyyaml, chardet, urllib3, PySocks, requests, langdetect
Successfully installed MarkupSafe-1.1.1 PySocks-1.7.1 Werkzeug-1.0.1 babel-2.9.0 certifi-2020.12.5 chardet-4.0.0 click-7.1.2 flask-1.1.2 flask-babel-2.0.0 idna-2.10 itsdangerous-1.1.0 jinja2-2.11.3 langdetect-1.0.8 lxml-4.6.3 pygments-2.8.0 python-dateutil-2.8.1 pytz-2021.1 pyyaml-5.4.1 requests-2.25.1 six-1.15.0 urllib3-1.26.4
```

I don't see `cryptography`.
