### ISSUE TITLE
Debian installation, ssl not working

### ISSUE THREAD

**Issue by rlex** [searx/searx#463]
Hello

I'm getting "certificate verification failed" on basically every ssl-enabled connection.

Trace:

```
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): www.google.com
ERROR:searx.webapp:Exception on / [POST]
Traceback (most recent call last):
  File "/opt/searx/searx-ve/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/searx/searx-ve/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/searx/searx-ve/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/searx/searx-ve/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/searx/searx-ve/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/searx/searx-ve/local/lib/python2.7/site-packages/searx-0.8.0-py2.7.egg/searx/webapp.py", line 382, in index
    search.search(request)
  File "/opt/searx/searx-ve/local/lib/python2.7/site-packages/searx-0.8.0-py2.7.egg/searx/search.py", line 294, in search
    engine.request(self.query.encode('utf-8'), request_params)
  File "/opt/searx/searx-ve/lib/python2.7/site-packages/searx-0.8.0-py2.7.egg/searx/engines/google.py", line 205, in request
    params['cookies']['PREF'] = get_google_pref_cookie()
  File "/opt/searx/searx-ve/lib/python2.7/site-packages/searx-0.8.0-py2.7.egg/searx/engines/google.py", line 141, in get_google_pref_cookie
    resp = get('https://www.google.com/ncr', allow_redirects=False)
  File "/opt/searx/searx-ve/local/lib/python2.7/site-packages/searx-0.8.0-py2.7.egg/searx/poolrequests.py", line 82, in get
    return request('get', url, **kwargs)
  File "/opt/searx/searx-ve/local/lib/python2.7/site-packages/searx-0.8.0-py2.7.egg/searx/poolrequests.py", line 75, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/opt/searx/searx-ve/local/lib/python2.7/site-packages/requests/sessions.py", line 461, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/searx/searx-ve/local/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/opt/searx/searx-ve/local/lib/python2.7/site-packages/requests/adapters.py", line 431, in send
    raise SSLError(e, request=request)
SSLError: [Errno bad handshake] [('SSL routines', 'SSL3_GET_SERVER_CERTIFICATE', 'certificate verify failed')]
```

Fixed by pip install certifi==2015.04.28, but that's very dirty hack.

**Comment by jason-speck** [comment]
I had the same issue, but only for google -- other engines worked fine.  The reporters workaround also "fixed" it for me.

**Comment by cy8aer** [comment]
hm, now it is not working for me anymore (debian jessie):

```
Traceback (most recent call last):
  File "/usr/share/searx/searx/__init__.py", line 55, in <module>
    environ['REQUESTS_CA_BUNDLE'] = certifi.old_where()
AttributeError: 'module' object has no attribute 'old_where'
```

**Comment by asciimoo** [comment]
@cy8aer what is your python/certifi version?

**Comment by cy8aer** [comment]
python 2.7.9, certifi 2015.04.28. Something too old (so need pip reinstall)? But 2015.04.28 looks to be used in comments above.

**Comment by cy8aer** [comment]
```
Python 2.7.9 (default, Mar  1 2015, 12:57:24) 
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import certifi
>>> certifi.old_where()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'old_where'
```

**Comment by cy8aer** [comment]
```
>>> dir(certifi)
['__builtins__', '__doc__', '__file__', '__name__', '__package__', '__path__', 'core', 'where']
```

**Comment by asciimoo** [comment]
Try to update certifi: `pip install --force certifi==2015.11.20.1`

**Comment by cy8aer** [comment]
hm, after realising that I am using a ve the system runs after upgrading to 2015.11.20.1. Thank you. That may not effect new installed environments but old installations (never touch a running system). Maybe a comment to upgrade to 2015.11.20.1 may be useful.
